# Generated by Django 3.2 on 2022-06-03 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='user.page')),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='user.policy')),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='user_id',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
