# Generated by Django 3.2 on 2022-06-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_query_queries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='query',
            new_name='query_set',
        ),
    ]
